CREATE TABLE "20082013motores" (
	"Año,Nombre,RNP,Estado,Municipio,Localidad,Monto_federal,Monto_estatal" VARCHAR(17) NOT NULL
);
CREATE TABLE "20082011reconversion" (
	"Año" INTEGER NOT NULL, 
	"Beneficiario" VARCHAR(62) NOT NULL, 
	"Nombre_proyecto" VARCHAR(151) NOT NULL, 
	"Tipo_proyecto" VARCHAR(155) NOT NULL, 
	"Especie" VARCHAR(40) NOT NULL, 
	"Estado" VARCHAR(34) NOT NULL, 
	"Municipio" VARCHAR(25) NOT NULL, 
	"Localidad" VARCHAR(47) NOT NULL, 
	"Monto" VARCHAR(22) NOT NULL, 
	_unnamed INTEGER
);
CREATE TABLE "20112013beneficiariosdiesel" (
	"ANO" INTEGER NOT NULL, 
	"NOMBRE" VARCHAR(26), 
	"PRIMER APELLIDO" VARCHAR(14), 
	"SEGUNDO APELLIDO" VARCHAR(17), 
	"RAZON SOCIAL" VARCHAR(87), 
	"CURP" VARCHAR(205), 
	"RFC" VARCHAR(205), 
	"RNP UNIDAD ECONOMICA" BIGINT, 
	"LOCALIDAD" VARCHAR(36) NOT NULL, 
	"MUNICIPIO" VARCHAR(22) NOT NULL, 
	"ENTIDAD" VARCHAR(31) NOT NULL, 
	"MONTO DE APOYO" FLOAT NOT NULL
);
CREATE TABLE "20112012pesca" (
	"Año" INTEGER NOT NULL, 
	"Beneficiario" VARCHAR(165), 
	"RNPA" VARCHAR(61), 
	"Especie" VARCHAR(70), 
	"Entidad" VARCHAR(19) NOT NULL, 
	"Municipio " VARCHAR(36), 
	"Localidad" VARCHAR(56), 
	"Monto_federal" FLOAT
);
CREATE TABLE "20112013Beneficiariosgasolina" (
	"ANO" INTEGER NOT NULL, 
	"PRIMER APELLIDO" VARCHAR(22), 
	"SEGUNDO APELLIDO" VARCHAR(14), 
	"NOMBRE" VARCHAR(24) NOT NULL, 
	"CURP" VARCHAR(205) NOT NULL, 
	"RNP ACTIVO PRODUCTIVO" INTEGER NOT NULL, 
	"LOCALIDAD" VARCHAR(45) NOT NULL, 
	"MUNICIPIO" VARCHAR(38) NOT NULL, 
	"ENTIDAD" VARCHAR(19) NOT NULL, 
	"MONTO DEL APOYO" FLOAT NOT NULL
);
CREATE TABLE "20112013Motorescomponentes" (
	"Componente,Año,Nombre,RNP,Estado,Municipio,Localidad,Monto_federal,Monto_estatal" VARCHAR(22) NOT NULL
);
CREATE TABLE "2011electricos" (
	"Año" INTEGER NOT NULL, 
	"Beneficiario" VARCHAR(37) NOT NULL, 
	"RNPA" BIGINT NOT NULL, 
	"Estado" VARCHAR(6) NOT NULL, 
	"Municipio" VARCHAR(10) NOT NULL, 
	"Localidad" VARCHAR(14) NOT NULL, 
	"Monto_federal" INTEGER NOT NULL, 
	"Monto_estatal" INTEGER NOT NULL
);
CREATE TABLE "2012integral" (
	"No" INTEGER NOT NULL, 
	"Beneficiario" VARCHAR(76) NOT NULL, 
	"RNPA" VARCHAR(64) NOT NULL, 
	"Nombre_proyecto" VARCHAR(156) NOT NULL, 
	"Tipo_apoyo" VARCHAR(32) NOT NULL, 
	"Especie" VARCHAR(73) NOT NULL, 
	"Estado" VARCHAR(19) NOT NULL, 
	"Municipio" VARCHAR(17) NOT NULL, 
	"Localidad" VARCHAR(30) NOT NULL, 
	"Monto_federal" INTEGER NOT NULL
);
CREATE TABLE "2012motoresmarinosecologicos2012" (
	"Año" INTEGER NOT NULL, 
	"Beneficiario" VARCHAR(72) NOT NULL, 
	"RNP" BIGINT NOT NULL, 
	"Localidad" VARCHAR(43) NOT NULL, 
	"Municipio" VARCHAR(22) NOT NULL, 
	"Estado" VARCHAR(4) NOT NULL, 
	"Aprobacion Conapesca" INTEGER NOT NULL, 
	"Aprobacion Gob. Edo." INTEGER NOT NULL
);
CREATE TABLE sustitucionmotores (
	"Año" INTEGER NOT NULL, 
	" Programa " VARCHAR(67) NOT NULL, 
	"Componente" VARCHAR(80) NOT NULL
);
CREATE TABLE "20082013motores" (
	"Año,Nombre,RNP,Estado,Municipio,Localidad,Monto_federal,Monto_estatal" VARCHAR(17) NOT NULL
);
CREATE TABLE "20082011reconversion" (
	"Año" INTEGER NOT NULL, 
	"Beneficiario" VARCHAR(62) NOT NULL, 
	"Nombre_proyecto" VARCHAR(151) NOT NULL, 
	"Tipo_proyecto" VARCHAR(155) NOT NULL, 
	"Especie" VARCHAR(40) NOT NULL, 
	"Estado" VARCHAR(34) NOT NULL, 
	"Municipio" VARCHAR(25) NOT NULL, 
	"Localidad" VARCHAR(47) NOT NULL, 
	"Monto" VARCHAR(22) NOT NULL, 
	_unnamed INTEGER
);
CREATE TABLE "20112013beneficiariosdiesel" (
	"ANO" INTEGER NOT NULL, 
	"NOMBRE" VARCHAR(26), 
	"PRIMER APELLIDO" VARCHAR(14), 
	"SEGUNDO APELLIDO" VARCHAR(17), 
	"RAZON SOCIAL" VARCHAR(87), 
	"CURP" VARCHAR(205), 
	"RFC" VARCHAR(205), 
	"RNP UNIDAD ECONOMICA" BIGINT, 
	"LOCALIDAD" VARCHAR(36) NOT NULL, 
	"MUNICIPIO" VARCHAR(22) NOT NULL, 
	"ENTIDAD" VARCHAR(31) NOT NULL, 
	"MONTO DE APOYO" FLOAT NOT NULL
);
CREATE TABLE "20112012pesca" (
	"Año" INTEGER NOT NULL, 
	"Beneficiario" VARCHAR(165), 
	"RNPA" VARCHAR(61), 
	"Especie" VARCHAR(70), 
	"Entidad" VARCHAR(19) NOT NULL, 
	"Municipio " VARCHAR(36), 
	"Localidad" VARCHAR(56), 
	"Monto_federal" FLOAT
);
CREATE TABLE "20112013Beneficiariosgasolina" (
	"ANO" INTEGER NOT NULL, 
	"PRIMER APELLIDO" VARCHAR(22), 
	"SEGUNDO APELLIDO" VARCHAR(14), 
	"NOMBRE" VARCHAR(24) NOT NULL, 
	"CURP" VARCHAR(205) NOT NULL, 
	"RNP ACTIVO PRODUCTIVO" INTEGER NOT NULL, 
	"LOCALIDAD" VARCHAR(45) NOT NULL, 
	"MUNICIPIO" VARCHAR(38) NOT NULL, 
	"ENTIDAD" VARCHAR(19) NOT NULL, 
	"MONTO DEL APOYO" FLOAT NOT NULL
);
CREATE TABLE "20112013Motorescomponentes" (
	"Componente,Año,Nombre,RNP,Estado,Municipio,Localidad,Monto_federal,Monto_estatal" VARCHAR(22) NOT NULL
);
CREATE TABLE "2011electricos" (
	"Año" INTEGER NOT NULL, 
	"Beneficiario" VARCHAR(37) NOT NULL, 
	"RNPA" BIGINT NOT NULL, 
	"Estado" VARCHAR(6) NOT NULL, 
	"Municipio" VARCHAR(10) NOT NULL, 
	"Localidad" VARCHAR(14) NOT NULL, 
	"Monto_federal" INTEGER NOT NULL, 
	"Monto_estatal" INTEGER NOT NULL
);
CREATE TABLE "2012integral" (
	"No" INTEGER NOT NULL, 
	"Beneficiario" VARCHAR(76) NOT NULL, 
	"RNPA" VARCHAR(64) NOT NULL, 
	"Nombre_proyecto" VARCHAR(156) NOT NULL, 
	"Tipo_apoyo" VARCHAR(32) NOT NULL, 
	"Especie" VARCHAR(73) NOT NULL, 
	"Estado" VARCHAR(19) NOT NULL, 
	"Municipio" VARCHAR(17) NOT NULL, 
	"Localidad" VARCHAR(30) NOT NULL, 
	"Monto_federal" INTEGER NOT NULL
);
CREATE TABLE "2012motoresmarinosecologicos2012" (
	"Año" INTEGER NOT NULL, 
	"Beneficiario" VARCHAR(72) NOT NULL, 
	"RNP" BIGINT NOT NULL, 
	"Localidad" VARCHAR(43) NOT NULL, 
	"Municipio" VARCHAR(22) NOT NULL, 
	"Estado" VARCHAR(4) NOT NULL, 
	"Aprobacion Conapesca" INTEGER NOT NULL, 
	"Aprobacion Gob. Edo." INTEGER NOT NULL
);
CREATE TABLE sustitucionmotores (
	"Año" INTEGER NOT NULL, 
	" Programa " VARCHAR(67) NOT NULL, 
	"Componente" VARCHAR(80) NOT NULL
);
