CREATE TABLE artedepescaretenidasprovisionalmente (
	"Entidad_Federativa" VARCHAR(19) NOT NULL, 
	"Año" INTEGER NOT NULL, 
	"Arte_Pesca_Incautadas" VARCHAR(6)
);
CREATE TABLE embarcacionesretenidasprovisionalmente (
	"Entidad_Federativa" VARCHAR(19) NOT NULL, 
	"Año" INTEGER NOT NULL, 
	"Embarcaciones_Incautadas" INTEGER NOT NULL
);
CREATE TABLE listadodenuncias (
	"Año" INTEGER NOT NULL, 
	"Estado" VARCHAR(19) NOT NULL, 
	"Municipio" VARCHAR(36), 
	"Localidad" VARCHAR(37), 
	"Lugar_Conocido" VARCHAR(50) NOT NULL, 
	"Estatus" VARCHAR(9) NOT NULL
);
CREATE TABLE numerodeoficialesfederalesdepesca (
	"Area_Adscripcion" VARCHAR(19) NOT NULL, 
	"Año" INTEGER NOT NULL, 
	"Numero_oficiales" INTEGER
);
CREATE TABLE numeroembarcaciones (
	"Entidad_Federativa" VARCHAR(19) NOT NULL, 
	"Tipo" VARCHAR(17) NOT NULL, 
	"Año" INTEGER NOT NULL, 
	"Numero_embarcaciones" INTEGER NOT NULL
);
CREATE TABLE pescailegal2013 (
	"Año" INTEGER, 
	"ESTADO" VARCHAR(19), 
	"ABULON" FLOAT, 
	"AGUA MALA- BOLA DE CANON" INTEGER, 
	"ALMEJA" FLOAT, 
	"ALMEJA CATARINA" FLOAT, 
	"ALMEJA CHOCOLATA" FLOAT, 
	"ALMEJA GENEROSA" INTEGER, 
	"BAGRE" FLOAT, 
	"CALAMAR" FLOAT, 
	"CALLO DE HACHA" FLOAT, 
	"CAMARON" FLOAT, 
	"CARACOL" FLOAT, 
	"CARPA" FLOAT, 
	"CHARAL" INTEGER, 
	"CURVINA GOLFINA" FLOAT, 
	"DORADO" FLOAT, 
	"ERIZO" INTEGER, 
	"ESCAMA GENERAL" FLOAT, 
	"JAIBA" FLOAT, 
	"JUREL" FLOAT, 
	_unnamed VARCHAR(32), 
	"LANGOSTA" FLOAT NOT NULL, 
	"LANGOSTINO" INTEGER NOT NULL, 
	"LISA-LISETA" FLOAT NOT NULL, 
	"LOBINA" FLOAT NOT NULL, 
	"MARLIN" FLOAT NOT NULL, 
	"MERO" FLOAT NOT NULL, 
	"OSTION" FLOAT NOT NULL, 
	"PELACICOS MENORES" INTEGER NOT NULL, 
	"PEPINO DE MAR" FLOAT NOT NULL, 
	"PEZ ESPADA" INTEGER NOT NULL, 
	"PEZ VELA" FLOAT NOT NULL, 
	"PULPO" FLOAT NOT NULL, 
	"ROBALO" FLOAT NOT NULL, 
	"SABALO" VARCHAR(4) NOT NULL, 
	"SIERRA" FLOAT NOT NULL, 
	"TIBURON Y RAYAS" FLOAT NOT NULL, 
	"TILAPIA" FLOAT NOT NULL, 
	"TRUCHA DE AGUADULCE" INTEGER NOT NULL, 
	"TUNIDOS" FLOAT NOT NULL, 
	"OTROS" FLOAT NOT NULL
);
CREATE TABLE pescailegal (
	"Año" INTEGER NOT NULL, 
	"ESTADO" VARCHAR(19) NOT NULL, 
	"ABULON" FLOAT, 
	"AGUA MALA- BOLA DE CANON" INTEGER NOT NULL, 
	"ALMEJA" FLOAT NOT NULL, 
	"ATUN" FLOAT NOT NULL, 
	"CALAMAR" FLOAT NOT NULL, 
	"CAMARON" FLOAT NOT NULL, 
	"CARACOL" FLOAT NOT NULL, 
	"DORADO" FLOAT NOT NULL, 
	"ESCAMA GENERAL" FLOAT NOT NULL, 
	"JAIBA" FLOAT NOT NULL, 
	"LANGOSTA" FLOAT NOT NULL, 
	"LISA-LISETA" FLOAT NOT NULL, 
	"MERO" FLOAT NOT NULL, 
	"OSTIÓN" FLOAT NOT NULL, 
	"PEPINO" FLOAT NOT NULL, 
	"PICUDOS" FLOAT NOT NULL, 
	"PULPO" FLOAT NOT NULL, 
	"ROBALO" FLOAT NOT NULL, 
	"TIBURON Y RAYAS" FLOAT NOT NULL, 
	"OTROS" FLOAT NOT NULL
);
CREATE TABLE recorridosinspeccion (
	"Año" INTEGER NOT NULL, 
	"Estado" VARCHAR(19) NOT NULL, 
	"Recorridos_Terrestres" FLOAT NOT NULL, 
	"Recorridos_Acuaticos" INTEGER NOT NULL, 
	"Personas_MP" INTEGER NOT NULL
);
CREATE TABLE totaldeactasyverificacionesdocumentales (
	"Entidades_Federativas" VARCHAR(19) NOT NULL, 
	"Año" INTEGER NOT NULL, 
	"Actas_Verificaciones" INTEGER NOT NULL
);
CREATE TABLE vehiculosretenidasprovisionalmente (
	"Entidad_Federativa" VARCHAR(19) NOT NULL, 
	"Año" INTEGER NOT NULL, 
	"Vehiculos_Incautadas" INTEGER NOT NULL
);
