CREATE TABLE sanciones (
	Ano DECIMAL NOT NULL, 
	Titular VARCHAR(99) NOT NULL, 
	Estado VARCHAR(19) NOT NULL, 
	MUNICIPIO VARCHAR(49) NOT NULL, 
	LOCALIDAD VARCHAR(49), 
	MOTIVO VARCHAR(43) NOT NULL, 
	Monto VARCHAR(11) NOT NULL
);
