CREATE TABLE embarcacionesextranjeras (
	"TITULAR" VARCHAR(63) NOT NULL, 
	"PAIS DE PROCEDENCIA" VARCHAR(4) NOT NULL, 
	"ESPECIE QUE AMPARA" VARCHAR(141) NOT NULL, 
	"AREA PARA LA CUAL SE DA EL TITULO" VARCHAR(47) NOT NULL, 
	"FECHA INICIO" DATE NOT NULL, 
	"FECHA TERMINO" DATE NOT NULL
);
CREATE TABLE embarcacionesmayores (
	"ESTADO" VARCHAR(53), 
	"MUNICIPIO" VARCHAR(21), 
	"LOCALIDAD" VARCHAR(25), 
	"RNPA" VARCHAR(11), 
	"TITULAR" VARCHAR(113), 
	"ESPECIE" VARCHAR(87), 
	"AREA" VARCHAR(561), 
	"FECHA_INICIO" DATE, 
	"FECHA_TERMINO" DATE
);
CREATE TABLE embarcacionesmenores (
	"ESTADO" VARCHAR(19), 
	"MUNICIPIO" VARCHAR(326), 
	"LOCALIDAD" VARCHAR(326), 
	"RNPA" VARCHAR(326), 
	"TITULAR" VARCHAR(106), 
	"ESPECIE" VARCHAR(216), 
	"AREA" VARCHAR(677), 
	"FECHA_INICIO" DATE, 
	"FECHA_TERMINO" VARCHAR(11)
);
