CREATE TABLE dieselmarino (
	"Año" INTEGER NOT NULL, 
	"Entidades Federativas" VARCHAR(19) NOT NULL, 
	"Solicitudes Recibidas" INTEGER, 
	"Activos con Consumos" INTEGER
);
CREATE TABLE "ANEXO12516RHPLANTILLAOFICIALESDEPESCA" (
	"AREA DE ADSCRIPCION" VARCHAR(15) NOT NULL, 
	"APELLIDO PATERNO" VARCHAR(19), 
	"APELLIDO MATERNO" VARCHAR(11) NOT NULL, 
	"NOMBRE  (S)" VARCHAR(22) NOT NULL, 
	"NOMBRE DEL PUESTO EN MAESTRO" VARCHAR(16) NOT NULL
);
CREATE TABLE "ANEXOJURIDICO12516" (
	"<New Sheet> 1 - 12516" INTEGER
);
CREATE TABLE "EMBARCACIONESASIGNADASPORENTIDADFEDERATIVAANEXO2" (
	"<New Sheet> 1 - Hoja1" VARCHAR(42) NOT NULL
);
CREATE TABLE "PRESUPUESTODGIV20142015ANEXO1" (
	"<New Sheet> 1 - Hoja1" VARCHAR(115) NOT NULL
);
CREATE TABLE "REPORTEDEDENUNCIASSIDEPI2014ANEXO4" (
	"Folio de denuncia" INTEGER NOT NULL, 
	"Fecha captura" DATE NOT NULL, 
	"Estado" VARCHAR(19) NOT NULL, 
	"Municipio" VARCHAR(24), 
	"Localidad" VARCHAR(43), 
	"Lugar conocido" VARCHAR(50) NOT NULL, 
	"Tipo de denuncia" VARCHAR(23) NOT NULL, 
	"Instrumento utilizado" VARCHAR(17) NOT NULL, 
	"Estatus" VARCHAR(11) NOT NULL, 
	"Especie" VARCHAR(12) NOT NULL
);
CREATE TABLE "REPORTEDEDENUNCIASSIDEPI2015ANEXO4" (
	"Folio de denuncia" INTEGER NOT NULL, 
	"Fecha captura" DATE NOT NULL, 
	"Estado" VARCHAR(19) NOT NULL, 
	"Municipio" VARCHAR(36), 
	"Localidad" VARCHAR(43), 
	"Lugar conocido" VARCHAR(50) NOT NULL, 
	"Tipo de denuncia" VARCHAR(23) NOT NULL, 
	"Instrumento utilizado" VARCHAR(17) NOT NULL, 
	"Estatus" VARCHAR(11) NOT NULL, 
	"Especie" VARCHAR(12) NOT NULL
);
CREATE TABLE "RESULTADOS20142015ANEXO3" (
	"<New Sheet> 1 - 2014" VARCHAR(88)
);
CREATE TABLE "1ANEXO1" (
	"Entidad" VARCHAR(19) NOT NULL, 
	"Solicitudes 2009 Permisos" INTEGER NOT NULL, 
	"Solicitudes 2009 Concesiones" INTEGER NOT NULL, 
	"Solicitudes 2012 Permisos" INTEGER NOT NULL, 
	"Solicitudes 2012 Concesiones" INTEGER NOT NULL, 
	"Solicitudes 2015 Permisos" INTEGER NOT NULL, 
	"Solicitudes 2015 Concesiones" INTEGER NOT NULL
);
CREATE TABLE "2ANEXO22012MAYORES" (
	"AÑO" INTEGER NOT NULL, 
	"ESTADO" VARCHAR(19) NOT NULL, 
	"MUNICIPIO" VARCHAR(15), 
	"LOCALIDAD" VARCHAR(25), 
	"RNP TITULAR" BIGINT NOT NULL, 
	"RAZÓN SOCIAL" VARCHAR(82) NOT NULL, 
	"ZONA DE OPERACIÓN" VARCHAR(433), 
	"RNP EMBARCACIÓN" INTEGER NOT NULL, 
	"EMBARCACIÓN" VARCHAR(27) NOT NULL, 
	"MATRÍCULA" VARCHAR(13) NOT NULL, 
	"PESQUERÍA" VARCHAR(87) NOT NULL, 
	"PERMISO" VARCHAR(14) NOT NULL, 
	"FECHA INICIO" DATE NOT NULL, 
	"FECHA TERMINO" DATE NOT NULL
);
CREATE TABLE "3ANEXO22015MAYORES" (
	"AÑO" INTEGER NOT NULL, 
	"RNPA TITULAR" BIGINT NOT NULL, 
	"RAZÓN SOCIAL" VARCHAR(68) NOT NULL, 
	"VIGENCIA INICIAL" DATE NOT NULL, 
	"VIGENCIA FINAL" DATE NOT NULL, 
	"NO. DE EMBARCACIONES" INTEGER NOT NULL, 
	"NOMBRE DE LA EMBARCACIÓN" VARCHAR(30) NOT NULL, 
	"MATRICULA DE LA EMBARCACION" VARCHAR(13) NOT NULL, 
	"RNPA DE LA EMBARCACIÓN" INTEGER NOT NULL, 
	"ESPECIE" VARCHAR(22) NOT NULL, 
	"ESTADO" VARCHAR(19) NOT NULL, 
	"MUNICIPIO" VARCHAR(15) NOT NULL, 
	"LOCALIDAD" VARCHAR(25) NOT NULL, 
	"ÁREA DE PESCA" VARCHAR(522) NOT NULL
);
CREATE TABLE "4ANEXO3" (
	"Entidad" VARCHAR(19) NOT NULL, 
	"Solicitudes 2009 Permisos " INTEGER NOT NULL, 
	"Solicitudes 2009 Concesiones" INTEGER NOT NULL, 
	"Solicitudes 2012 ermisos" INTEGER NOT NULL, 
	"Solicitudes 2012Concesiones" INTEGER NOT NULL, 
	"Solicitudes 2015Permisos" INTEGER NOT NULL, 
	"Solicitudes 2015Concesiones" INTEGER NOT NULL
);
CREATE TABLE "5ANEXO42012MENORES" (
	"AÑO " INTEGER NOT NULL, 
	"ESTADO" VARCHAR(19) NOT NULL, 
	"MUNICIPIO" VARCHAR(21) NOT NULL, 
	"LOCALIDAD" VARCHAR(34), 
	" RNP TITULAR" BIGINT NOT NULL, 
	"TITULAR" VARCHAR(92) NOT NULL, 
	"PESQUERIA" VARCHAR(27) NOT NULL, 
	"FECHA INICIO" DATE, 
	"FECHA TERMINO" VARCHAR(10), 
	"N°  EMB. " INTEGER, 
	"NOMBRE EMBARCACIÓN" VARCHAR(30), 
	"MATRICULA" VARCHAR(12), 
	"ZONA DE PESCA" VARCHAR(450)
);
CREATE TABLE "ANEXOORDENAMIENTO12316" (
	"Año Solicitud" INTEGER NOT NULL, 
	"Entidad" VARCHAR(19) NOT NULL, 
	"Permisos" INTEGER, 
	"Concesiones" INTEGER
);
CREATE TABLE "AvisosArriboNacional2014" (
	"ENTIDAD FEDERATIVA" VARCHAR(19) NOT NULL, 
	"CLAVE SITIO DE DESEMBARQUE" VARCHAR(25) NOT NULL, 
	"NOMBRE SITIO DE DESEMBARQUE" VARCHAR(72) NOT NULL, 
	"LUGAR DE CAPTURA" VARCHAR(54) NOT NULL, 
	"CLAVE LUGAR DE CAPTURA" VARCHAR(25) NOT NULL, 
	"CLAVE OFICINA" INTEGER NOT NULL, 
	"OFICINA" VARCHAR(25) NOT NULL, 
	"MES" VARCHAR(10) NOT NULL, 
	"AÑO" INTEGER NOT NULL, 
	"NOMBRE PRINCIPAL" VARCHAR(18) NOT NULL, 
	"CLAVE ESPECIE" VARCHAR(8) NOT NULL, 
	"NOMBRE ESPECIE" VARCHAR(50) NOT NULL, 
	"PESO DESEMBARCADO" FLOAT NOT NULL, 
	"PESO VIVO" FLOAT NOT NULL, 
	"VALOR" FLOAT NOT NULL, 
	"LITORAL" VARCHAR(14) NOT NULL
);
CREATE TABLE "AvisosArriboNacional2015" (
	"ENTIDAD FEDERATIVA" VARCHAR(19) NOT NULL, 
	"CLAVE SITIO DESEMBARQUE" VARCHAR(25) NOT NULL, 
	"NOMBRE SITIO DESEMBARQUE" VARCHAR(57) NOT NULL, 
	"CLAVE LUGAR DE CAPTURA" VARCHAR(25) NOT NULL, 
	"LUGAR DE CAPTURA" VARCHAR(58) NOT NULL, 
	"CLAVE OFICINA" INTEGER NOT NULL, 
	"OFICINA" VARCHAR(24) NOT NULL, 
	"MES" VARCHAR(10) NOT NULL, 
	"AÑO" INTEGER NOT NULL, 
	"NOMBRE PRINCIPAL" VARCHAR(18) NOT NULL, 
	"CLAVE ESPECIE" VARCHAR(8) NOT NULL, 
	"NOMBRE ESPECIE" VARCHAR(50) NOT NULL, 
	"PESO DESEMBARCADO" FLOAT NOT NULL, 
	"PESO VIVO" FLOAT NOT NULL, 
	"VALOR" FLOAT NOT NULL, 
	"LITORAL" VARCHAR(14) NOT NULL
);
