CREATE TABLE diesel (
	Ano DECIMAL NOT NULL, 
	Beneficiario VARCHAR(119) NOT NULL, 
	RFC VARCHAR(13), 
	RNPA DECIMAL, 
	Estado VARCHAR(31) NOT NULL, 
	Municipio VARCHAR(22) NOT NULL, 
	Localidad VARCHAR(36) NOT NULL, 
	Monto VARCHAR(15) NOT NULL
);
