CREATE TABLE integral (
	Ano DECIMAL NOT NULL, 
	Beneficiario VARCHAR(76) NOT NULL, 
	RNPA VARCHAR(64) NOT NULL, 
	Nombre_proyecto VARCHAR(156) NOT NULL, 
	Tipo_apoyo VARCHAR(32) NOT NULL, 
	Especie VARCHAR(73) NOT NULL, 
	Estado VARCHAR(19) NOT NULL, 
	Municipio VARCHAR(17) NOT NULL, 
	Localidad VARCHAR(30) NOT NULL, 
	Monto_federal DECIMAL NOT NULL
);
